version: "3.0"
services:
  server:
    build: .
    volumes:
      - ./src:/go/src/server
    ports:
      - 80:80
    tty: true
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: game
      MYSQL_USER: game
      MYSQL_PASSWORD: game
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-use-native-aio=0 --explicit_defaults_for_timestamp
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
